# 日志保存路径，默认…/logs/app. log
LOG_FILE:
# 日志文件最大大小，单位为MB
LOG_FILE_MAX_SIZE: 20
# 日志文件最大备份计数
LOG_FILE_BACKUP_COUNT: 5
# 日志格式
LOG_FORMAT: '%(asctime)s - %(levelname)s - [%(processName)s:%(process)d][%(threadName)s:%(thread)d][%(pathname)s:%(lineno)d] - %(message)s'